### PR TITLE
PR for Past Edition

### PR DESCRIPTION
**Pull request by linibensonjr**

### CODE REVIEW

**Comment by jeafreezy** [comment]
Kindly review @vickystickz

**Comment by vickystickz** [comment]
@linibensonjr Nice PR but the PastEdition component section still needs some touches:

- The Past edition could well aligned well in the middle so that the whole card is evident enough
Screenshot (7)

- The slider also needs to scroll when forward or backward icon is clicked
- The forward and backward icons are not aligned perfectly well to the middle of the round wrapper
Screenshot (11)

- Try to move onclick event to the icon wrapper also
- To use onclick events on the PastEdition component, you can add"  'use client' " to the top of the file before all imports
Screenshot (9)


- The PastEdition card shouldn't be iframe but a card that can take users to the Youtube video page directly and not have it played on the webpage directly or If you want to still use the iframe users should be able to view the video in full screen once they tap on the full screen icon on the iframe.
- You should also add the Past edition page to the "app" folder like the teams page and call for speakers page 
Screenshot (12)

- The past edition page should also have a filter feature as it appears on the design 
Screenshot (8)

Please let me know if you need more clarification

**Comment by jeafreezy** [comment]
Fixing all these isseues on the linibensonjr-dev-2023 branch

**Comment by linibensonjr** [comment]
Thank you @jeafreezy 🙌

**Comment by jeafreezy** [comment]
I think I have fixed all these issues.

Some decisions I made:

- I left the PastEditionCard as Iframe because I believe it's much better and faster, since we can just insert the link to the video on YouTube. If we are to use an image of each session, that will require us to export all the images from Figma and the Asset folder will become very large considering that there will be more sessions to add going forward.
- I removed the forward and backward nav on the homepage and returned the browser scrollbar (restyled it). So if the user want to see the past editions, they should use it to scroll to the side. Or they should click on the button to 'Explore more'. That way they will be taken to the past edition page and have access to all of them. Another reason is to avoid installing a library to make it happen and to also save some time of implementing a custome one. We have some other priority stuffs to work on. If time permits, we can revisit it.

**Pull request merged**
