### PR TITLE
Add Speakers Component

### PR DESCRIPTION
**Pull request by linibensonjr**

### CODE REVIEW

**Comment by vickystickz** [comment]
Hi @linibensonjr,  Well-done and great Job, After review, I noticed that :

- The speaker section does not align with the desktop spacing like other section 
- The speaker cards does not have enough gaps on laptop view 
- I noticed some part of the image link rendering below the Speakers picture frame
- The color around the speaker's picture frame has gradient color not just one color
- The top right edge of the frame is not rounded also

Kindly, see the screenshot below or checkout  the development link: [](https://gisfest-conference-website-git-fork-lin-0742d8-spatialnode-team.vercel.app/)

Screenshot (70)
You can do well to check the design to make adjustments.

**Comment by linibensonjr** [comment]
Okay thanks. I'll work on the feedbacks

**Comment by jeafreezy** [comment]
Thanks for the review @vickystickz !

**Comment by linibensonjr** [comment]
Hi @vickystickz @jeafreezy could you review the new PR? Thanks

**Comment by vickystickz** [comment]
@linibensonjr Nice contributions 
I have checked your PR.

Some Changes I noticed:

- I noticed the Conference Speakers component is not dynamic for passing any avatar picture as props
- The hover effect moves the pictures up and does not zoom in as prototyped on the design 
Hove effect


- You should use the Image tag and not as background image for a div tag. The image would be easy to manipulate well enough for the hover effect

**Comment by linibensonjr** [comment]
@vickystickz Could you review? 😁

**Comment by jeafreezy** [comment]
Great improvement @linibensonjr .

In the <Link> in the Speakers.tsx component
 Make the link dynamic,  let it come from the site configuration .

The one that has the call to action of "Become a speaker"

**Comment by linibensonjr** [comment]
Okay, I can still use the same url?

**Comment by jeafreezy** [comment]
> Okay, I can still use the same url?

Yes, you can. But let it be coming from the site Configuration.

I assume it will be an internal route when we develop the page for the call for participation. E.g /calls 

So when It is from the site configuration we can always update anytime without needing to touch the component.


Also, let the the text i.e "Become a Speaker", come from the site configuration file as well.


That's the idea.

**Comment by linibensonjr** [comment]
Okay, that makes sense. I'll fix it now

**Pull request merged**
